version: '3'
services:
  web:
    build: ./web
    ports:
      - "9013:80"
    restart: always
  service:
    build: ./service
    volumes:
      - ./service:/myapp
    # ports:
    #   - "9014:3000"
    restart: always