development:
  adapter: postgresql
  database: d4amicjclnlglg
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: d4amicjclnlglg
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: d4amicjclnlglg
  pool: 5
  timeout: 5000